name: Notes_CI-CD_SCD_A2_Scheduled_Tasks

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Check Website Status
        run: |
          if curl --head --fail --silent https://notes-scd.web.app; then
            echo "Website is up!"
          else
            echo "Website is down!"
          fi
